name: Marta Bil
title: User guide
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: martabil/just-the-docs

color_scheme: light

# logo: "https://www.dreamstime.com/user-guide-papers-icon-flat-style-illustration-vector-web-design-image152750570" 

aux_links:
  "Source repository on GitHub":
    - "//github.com/martabil/martabil.github.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw). The content is based on Felicity Brand's example DITA project."