name: Marta Bil
title: Homework
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: martabil/just-the-docs

color_scheme: dark

# logo: "/assets/images/Morris_badge.png 

aux_links:
  "Source repository on GitHub":
    - "//github.com/martabil/martabil.github.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of homework for the Technical Communication course at Vistula University (Warsaw). 